Bump @redhat-cloud-services/frontend-components from 3.9.29 to 3.9.32 (#3444)
* Bump @redhat-cloud-services/frontend-components from 3.9.29 to 3.9.32

Bumps [@redhat-cloud-services/frontend-components](https://github.com/RedHatInsights/frontend-components) from 3.9.29 to 3.9.32.
- [Release notes](https://github.com/RedHatInsights/frontend-components/releases)
- [Commits](https://github.com/RedHatInsights/frontend-components/commits)

---
updated-dependencies:
- dependency-name: "@redhat-cloud-services/frontend-components"
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* add ParamType for params

fixes a bunch of new type errors:

    Error: src/components/collection-dependencies-list/collection-usedby-dependencies-list.tsx(123,31): error TS2345: Argument of type 'object' is not assignable to parameter of type 'Record<string, string | boolean>'.
    Error: src/components/collection-detail/collection-content-list.tsx(124,21): error TS2345: Argument of type 'object' is not assignable to parameter of type 'Record<string, string | boolean>'.
      Index signature for type 'string' is missing in type '{}'.
    Error: src/components/headers/collection-header.tsx(590,62): error TS2345: Argument of type 'object' is not assignable to parameter of type 'Record<string, string | boolean>'.
    Error: src/components/headers/collection-header.tsx(595,71): error TS2345: Argument of type 'object' is not assignable to parameter of type 'Record<string, string | boolean>'.
    Error: src/components/headers/collection-header.tsx(603,11): error TS2345: Argument of type 'object' is not assignable to parameter of type 'Record<string, string | boolean>'.
    Error: src/components/headers/collection-header.tsx(609,71): error TS2345: Argument of type 'object' is not assignable to parameter of type 'Record<string, string | boolean>'.
    Error: src/components/headers/collection-header.tsx(617,11): error TS2345: Argument of type 'object' is not assignable to parameter of type 'Record<string, string | boolean>'.
    ERROR: "lint:ts" exited with 2.

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Martin Hradil <mhradil@redhat.com>