tsconfig - set module 2020 to allow dynamic imports
    src/l10n.ts:13:30 - error TS1323: Dynamic imports are only supported when the '--module' flag is set to 'es2020', 'esnext', 'commonjs', 'amd', 'system', or 'umd'.

    13   const { messages } = await import(`src/../locale/${locale}.js`);
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~