galaxykit: patch out wait_for_task, no task for deletion in 4.5
galaxykit#53 introduced a wait that doesn't work in 4.5 - deletion doesn't return a task yet,
but it was already released in 0.8.0, causes 1 UI tests failure:

    1) Collection Upload Tests
        "before all" hook for "user should not be able to upload new collection without permissions":
      CypressError: `cy.exec('galaxykit -s 'http://localhost:8002/api/galaxy/' -u admin -p admin collection delete ansible network')` failed because the command exited with a non-zero code.

    Traceback (most recent call last):
      File "/home/runner/.local/bin/galaxykit", line 8, in <module>
        sys.exit(main())
      File "/home/runner/.local/lib/python3.8/site-packages/galaxykit/command.py", line 692, in main
        resp = collections.delete_collection(
      File "/home/runner/.local/lib/python3.8/site-packages/galaxykit/collections.py", line 197, in delete_collection
        wait_for_task(client, resp)
      File "/home/runner/.local/lib/python3.8/site-packages/galaxykit/utils.py", line 29, in wait_for_task
        url = urljoin(api_client.galaxy_root, task["task"])
    KeyError: 'task'

=> patch out wait_for_task in galaxykit, replace with empty function