test fix - collection_upload "collection should be uploaded"
fails on master now,

    Collection Upload Tests
    ✓ should not upload new collection version in collection list when user does not have permissions (24119ms)
    ✓ should not upload new collection version in collection detail when user does not have permissions
    ✓ should see upload new collection version in collection list when user does have permissions
    ✓ should see upload new collection version in collection detail when user does have permissions
    ✓ user should not be able to upload new collection without permissions
    1) collection should be uploaded
    ✓ should not upload new collection version when user does not have permissions
    ✓ should deprecate let user deprecate and undeprecate collections (5678ms)

    7 passing (1m)
    1 failing

    1) Collection Upload Tests
         collection should be uploaded:
       AssertionError: Timed out retrying after 4000ms: Expected to find content: 'Completed' within the element: <span.pf-c-label__content> but never did.
        at Context.eval (http://localhost:8002/__cypress/tests?p=cypress/integration/collection_upload.js:183:58)

trying to debug/fix

No-Issue