test fix - imports_filter "before each" hook for "exact filter for name is working." (#2165)
* fix imports_filter test

    Imports filter test
     ✓ should display success info after importing collection (21515ms)
     ✓ should fail on importing existing collection (5266ms)
     ✓ should redirect to new uploaded collection
     ✓ should be able to switch between namespaces
     ✓ partial filter for name is working.
     1) "before each" hook for "exact filter for name is working."

    5 passing (44s)
    1 failing

    1) Imports filter test
       "before each" hook for "exact filter for name is working.":
       Error: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
       > Request failed with status code 403

looks like partial is not waiting for the right request (probably catching the on load one)
=> adding keywords to distinguish the right one

No-Issue

* imports_filter - allow more params

    /api/automation-hub/_ui/v1/collection-versions/?namespace=arista&name=avd&version=3.0.0&offset=0&limit=10

* ensure galaxykit happens in before, not in  random tests

* add missing upload, drop redirect test which doesnt currently test anything

* galaxykit fails on dup collection upload, but we want that here

* dup intercepts