imports_filter - validation means no import failure on duplicates
trying to import an existing collection the second time fails on upload validation now, instead of failing on import
making this test obsolete, which is why it breaks trying to find a Failed import

    File "/home/himdel/galaxykit/galaxykit/collections.py", line 153, in upload_artifact
      resp = client._http("post", n_url, data=data, headers=headers)
    File "/home/himdel/galaxykit/galaxykit/client.py", line 211, in _http
      raise GalaxyClientError(resp, *json["errors"])
    galaxykit.utils.GalaxyClientError: {'status': '400', 'code': 'invalid', 'title': 'Invalid input.', 'detail': 'Collection test1.test2-1.0.0 already exists'}

No-Issue