package.json: switch from webpack-dev-server to webpack serve
because #439 updated webpack-cli from 3.x to 4.x and the command changed

webpack-dev-server still gets installed, but fails with..

    $  npm run start-standalone

    > ansible-hub-ui@0.1.0 start-standalone /home/himdel/ansible-hub-ui
    > NODE_ENV=development webpack-dev-server --host 0.0.0.0 --config config/standalone.dev.webpack.config.js

    internal/modules/cjs/loader.js:883
    throw err;
    ^

    Error: Cannot find module 'webpack-cli/bin/config-yargs'
    Require stack:
    - /home/himdel/ansible-hub-ui/node_modules/webpack-dev-server/bin/webpack-dev-server.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
        at Function.Module._load (internal/modules/cjs/loader.js:725:27)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)
        at Object.<anonymous> (/home/himdel/ansible-hub-ui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
        '/home/himdel/ansible-hub-ui/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
    ]
    }
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! ansible-hub-ui@0.1.0 start-standalone: `NODE_ENV=development webpack-dev-server --host 0.0.0.0 --config config/standalone.dev.webpack.config.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the ansible-hub-ui@0.1.0 start-standalone script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/himdel/.npm/_logs/2021-05-17T22_20_33_435Z-debug.log