fix ts errorrs
    > tsc

    src/components/patternfly-wrappers/l10n.tsx:21:4 - error TS2322: Type '{ children?: ReactNode; className?: string; defaultIsOpen?: boolean; expandedText: string; collapsedText: string; categoryName?: string; 'aria-label'?: string; numChips?: number; isClosable?: boolean; ... 370 more ...; ouiaSafe?: boolean; }' is not assignable to type 'IntrinsicClassAttributes<ChipGroup>'.
      Types of property 'ref' are incompatible.
        Type 'LegacyRef<HTMLUListElement>' is not assignable to type 'LegacyRef<ChipGroup>'.
          Type '(instance: HTMLUListElement) => void' is not assignable to type 'LegacyRef<ChipGroup>'.
            Type '(instance: HTMLUListElement) => void' is not assignable to type '(instance: ChipGroup) => void'.
              Types of parameters 'instance' and 'instance' are incompatible.
                Type 'ChipGroup' is missing the following properties from type 'HTMLUListElement': compact, type, addEventListener, removeEventListener, and 292 more.

    21   <PFChipGroup
          ~~~~~~~~~~~

    src/components/patternfly-wrappers/l10n.tsx:29:4 - error TS2322: Type '{ className?: string; hoverTip: string; clickTip: string; textAriaLabel: string; toggleAriaLabel: string; isReadOnly?: boolean; isExpanded?: boolean; isCode?: boolean; isBlock?: boolean; variant?: "inline" | ... 2 more ... | "inline-compact"; ... 374 more ...; key?: Key; }' is not assignable to type 'IntrinsicClassAttributes<ClipboardCopy>'.
      Types of property 'ref' are incompatible.
        Type 'LegacyRef<HTMLDivElement>' is not assignable to type 'LegacyRef<ClipboardCopy>'.
          Type '(instance: HTMLDivElement) => void' is not assignable to type 'LegacyRef<ClipboardCopy>'.
            Type '(instance: HTMLDivElement) => void' is not assignable to type '(instance: ClipboardCopy) => void'.
              Types of parameters 'instance' and 'instance' are incompatible.
                Type 'ClipboardCopy' is missing the following properties from type 'HTMLDivElement': align, addEventListener, removeEventListener, accessKey, and 291 more.

    29   <PFCopy
          ~~~~~~

    src/components/patternfly-wrappers/l10n.tsx:53:4 - error TS2322: Type '{ children?: ReactNode; className?: string; defaultIsOpen?: boolean; expandedText: string; collapsedText: string; categoryName?: string; 'aria-label'?: string; numLabels?: number; isClosable?: boolean; ... 373 more ...; key?: Key; }' is not assignable to type 'IntrinsicClassAttributes<LabelGroup>'.
      Types of property 'ref' are incompatible.
        Type 'LegacyRef<HTMLUListElement>' is not assignable to type 'LegacyRef<LabelGroup>'.
          Type '(instance: HTMLUListElement) => void' is not assignable to type 'LegacyRef<LabelGroup>'.
            Type '(instance: HTMLUListElement) => void' is not assignable to type '(instance: LabelGroup) => void'.
              Types of parameters 'instance' and 'instance' are incompatible.
                Type 'LabelGroup' is missing the following properties from type 'HTMLUListElement': compact, type, addEventListener, removeEventListener, and 292 more.

    53   <PFLabelGroup
          ~~~~~~~~~~~~

    Found 3 errors in the same file, starting at: src/components/patternfly-wrappers/l10n.tsx:21