[stable-4.5] Bump @redhat-cloud-services/frontend-components-config from 4.7.2 to 5.0.1 (#3802)
* [stable-4.5] Bump @redhat-cloud-services/frontend-components-config

Bumps [@redhat-cloud-services/frontend-components-config](https://github.com/RedHatInsights/frontend-components) from 4.7.2 to 5.0.1.
- [Commits](https://github.com/RedHatInsights/frontend-components/commits)

---
updated-dependencies:
- dependency-name: "@redhat-cloud-services/frontend-components-config"
  dependency-type: direct:development
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* add ParamType for params

fixes a bunch of new type errors:

    Error: src/components/collection-dependencies-list/collection-usedby-dependencies-list.tsx(123,31): error TS2345: Argument of type 'object' is not assignable to parameter of type 'Record<string, string | boolean>'.
    Error: src/components/collection-detail/collection-content-list.tsx(124,21): error TS2345: Argument of type 'object' is not assignable to parameter of type 'Record<string, string | boolean>'.
      Index signature for type 'string' is missing in type '{}'.
    Error: src/components/headers/collection-header.tsx(590,62): error TS2345: Argument of type 'object' is not assignable to parameter of type 'Record<string, string | boolean>'.
    Error: src/components/headers/collection-header.tsx(595,71): error TS2345: Argument of type 'object' is not assignable to parameter of type 'Record<string, string | boolean>'.
    Error: src/components/headers/collection-header.tsx(603,11): error TS2345: Argument of type 'object' is not assignable to parameter of type 'Record<string, string | boolean>'.
    Error: src/components/headers/collection-header.tsx(609,71): error TS2345: Argument of type 'object' is not assignable to parameter of type 'Record<string, string | boolean>'.
    Error: src/components/headers/collection-header.tsx(617,11): error TS2345: Argument of type 'object' is not assignable to parameter of type 'Record<string, string | boolean>'.
    ERROR: "lint:ts" exited with 2.

(cherry picked from commit bad016173fff2c86841b98b5630eed26a3481bae, #3444)

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Martin Hradil <mhradil@redhat.com>