Fix task_management_detail sporadic failure (#1985)
Task detail "before all" hook for "contains correct headers and field names.":
    CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `remotes`. No request ever occurred.

No-Issue

(cherry picked from commit d5294ff1d37cc85d08169217a599119b630dc707)