[stable-4.5] cypress.yml - backport changes from master (#2480) (#2498)
* cypress.yml - backport changes from master

Backports cypress.yml changes from #2480, #2478, #2240, #1979
(+ associated workflow scripts from #2240)

No-Issue

* build from pulp-ci-centos 3.18, not latest (current 4.5 uses pulpcore==3.18.6)

* fix pip install python-ldap failing on missing lber.h

    Building wheels for collected packages: galaxy-ng, python-ldap
    ...
      Building wheel for python-ldap (pyproject.toml): finished with status 'error'
    ...
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DHAVE_SASL -DHAVE_TLS -DLDAPMODULE_VERSION=3.4.2 "-DLDAPMODULE_AUTHOR=python-ldap project" "-DLDAPMODULE_LICENSE=Python style" -IModules -I/usr/include/python3.8 -c Modules/LDAPObject.c -o build/temp.linux-x86_64-cpython-38/Modules/LDAPObject.o
          In file included from Modules/LDAPObject.c:3:
          Modules/common.h:15:10: fatal error: lber.h: No such file or directory
          #include <lber.h>
                    ^~~~~~~~
          compilation terminated.

* test fix - collection_upload "collection should be uploaded" (#2164)

* test fix - collection_upload "collection should be uploaded"

fails on master now,

    Collection Upload Tests
    ✓ should not upload new collection version in collection list when user does not have permissions (24119ms)
    ✓ should not upload new collection version in collection detail when user does not have permissions
    ✓ should see upload new collection version in collection list when user does have permissions
    ✓ should see upload new collection version in collection detail when user does have permissions
    ✓ user should not be able to upload new collection without permissions
    1) collection should be uploaded
    ✓ should not upload new collection version when user does not have permissions
    ✓ should deprecate let user deprecate and undeprecate collections (5678ms)

    7 passing (1m)
    1 failing

    1) Collection Upload Tests
         collection should be uploaded:
       AssertionError: Timed out retrying after 4000ms: Expected to find content: 'Completed' within the element: <span.pf-c-label__content> but never did.
        at Context.eval (http://localhost:8002/__cypress/tests?p=cypress/integration/collection_upload.js:183:58)

trying to debug/fix

No-Issue

* collection_upload test: replace ansible-network with ansible-posix for testing

ansible-network is using `requires_ansible: '*'`,
which no longer passes validation since galaxy-importer 0.4.5 (https://issues.redhat.com/browse/AAH-981)

so it fails the test by failing to import
=> replacing with ansible-posix

(cherry picked from commit 38b816e19d3f3d75d7bc0227a24a03d8363090ec)

* pulpPrefix - set to /pulp/api/v3/

not API_BASE_PATH + /pulp/api/v3/ .. that's 4.6+

* update cache key