[PR #1985/d5294ff1 backport][stable-4.5] Fix task_management_detail sporadic failure (#2035)
* Fix task_management_detail sporadic failure (#1985)

Task detail "before all" hook for "contains correct headers and field names.":
    CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `remotes`. No request ever occurred.

No-Issue

(cherry picked from commit d5294ff1d37cc85d08169217a599119b630dc707)

* task* tests .. wait for first remotes load, then intercept, then click Sync

meant to fix everything in task_list failing,
and sync with #1985 changes

(cherry picked from commit f55937aa0c9a3765a0b5d3f68b434a74265c875c)

Co-authored-by: Martin Hradil <mhradil@redhat.com>